export default [
	{ name: '热销',
	description: '热销',
	restaurant_id: null,
	id: null,
	foods: [] },
	{ name: '优惠',
	description: '优惠',
	restaurant_id: null,
	id: null,
	foods: [] },
	{ name: '新品',
	description: '新品',
	restaurant_id: null,
	id: null,
	foods: [] },
	{ name: '招牌',
	description: '招牌',
	restaurant_id: null,
	id: null,
	foods: [] },
	{ name: '必点',
	description: '必点',
	restaurant_id: null,
	id: null,
	foods: [] },
	{ name: '其他',
	description: '其他',
	restaurant_id: null,
	id: null,
	foods: [] }
]